# permissions for end users to edit releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: release-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: relis
    app.kubernetes.io/part-of: relis
    app.kubernetes.io/managed-by: kustomize
  name: release-editor-role
rules:
- apiGroups:
  - konflux.redhat.com
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konflux.redhat.com
  resources:
  - releases/status
  verbs:
  - get
